name: First Workflow
on:
  push:
    branches: 
      - main

jobs:
  example-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome mssg
        run: echo "welcome to our first github actions workflow"
        
